name: Push Na branch Main ou Master

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Install jest
      run: npm install jest supertest
    - name: Fix permissions
      run: sudo chmod -R 777 /home/runner/.npm/_npx
    - name: Run SuperTest
      run: npm run test:single