name: Push Na branch Main ou Master

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Install supertest
      run: npm install supertest --save-dev
    - name: Run SuperTest
      run: npx jest --testNamePattern="cadastrar uma reserva"